{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Database RPS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(db_query_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (op) (rate(redis_operation_seconds_sum[5m]))\r\n  /\r\n  sum by (op) (rate(redis_operation_seconds_count[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Avg Response Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_response_size_bytes_sum{handler!=\"none\"}[5m]))\r\n/\r\nsum by (handler) (rate(http_response_size_bytes_count{handler!=\"none\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(db_query_duration_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, op) (rate(redis_operation_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "ceil(sum by (method) (increase(http_requests_total{method=~\"GET|POST|PATCH|DELETE\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(db_query_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(db_query_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by (op, status) (rate(redis_operation_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by (handler, method) (rate(http_requests_total{handler!=\"none\", method!~\"OPTIONS|HEAD\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}